Update README.md
trapacska/temp-01 pull request #1
Opened 2019-03-01 09:16 UTC by trapacska

2019-03-01 09:30 UTC, lpusok commented on README.md
> +- The step should find out what trigger_event_type if the actual build:
What if build started manually?

2019-03-01 09:30 UTC, lpusok commented on README.md
> +- If the previous build is failed then export an env, for example: `PREVIOUS_BUILD_FAILED=true`
If previous build aborted, how will handle that?

2019-03-01 09:30 UTC, lpusok commented on README.md
> +- BITRISE_PULL_REQUEST
Could add a new env var, which is set by website.

2019-03-01 09:37 UTC, BirmacherAkos reviewed
I have the same comments like Laci

2019-03-01 10:24 UTC, godrei commented on README.md
> +- If the previous build is failed then export an env, for example: `PREVIOUS_BUILD_FAILED=true`
what about `PREVIOUS_BUILD_STATUS`
- <empty> - no prev build for the same start event
- success
- failed
- aborted

2019-03-01 10:25 UTC, godrei requested changes
Also please add example, how the actual build's steps would use the exposed env

2019-03-01 10:26 UTC, lszucs reviewed
Nothing to add to previous comments. Looks good generally though!

2019-03-06 11:29 UTC, trapacska commented on README.md
> +- BITRISE_PULL_REQUEST
?

2019-03-06 12:28 UTC, lszucs reviewed
LGTM

2019-03-07 11:29 UTC, BirmacherAkos requested changes
typo

2019-03-07 11:29 UTC, BirmacherAkos commented on README.md
> +- If the previous build is failed then export an env witht he status, for example: `PREVIOUS_BUILD_STATUS=[success or failed or aborted]`
typo: export an env **witht he** status => export an env **with the** status

2019-03-07 11:39 UTC, BirmacherAkos approved these changes

2019-03-07 11:52 UTC, lpusok commented on README.md
> +- BITRISE_PULL_REQUEST
I mean implement change detection on website logic.

2019-03-07 12:51 UTC, lpusok reviewed
left comment

2019-03-07 12:51 UTC, lpusok commented on README.md
> +- The step should find out what trigger_event_type if the actual build:
Isn't BITRISE_GIT_COMMIT always set? Meaning is there a difference between push and manual?

2019-03-07 15:30 UTC, trapacska commented on README.md
> +- The step should find out what trigger_event_type if the actual build:
not always set. if you start a build you start it by branch

2019-03-08 08:46 UTC, godrei approved these changes

2019-03-08 09:45 UTC, BirmacherAkos approved these changes

2019-03-08 09:48 UTC, lpusok reviewed
ok

2019-03-08 10:31 UTC, lszucs reviewed
LGTM

2019-03-08 10:52 UTC, merged